tabWidth: 2
useTabs: false
semi: true
singleQuote: false
jsxSingleQuote: false
bracketSpacing: true
bracketSameLine: false
# keep prettier 1.x defaults to avoid reformatting the codebase
trailingComma: none
arrowParens: avoid
