const actionTypes = {
  TABLE_LOADING_DATA: "TABLE_LOADING_DATA",
  TABLE_DATA_LOADED: "TABLE_DATA_LOADED",
  TABLE_DATA_LOAD_ERROR: "TABLE_DATA_LOAD_ERROR",
  COLUMNS_LOADING_DATA: "COLUMNS_LOADING_DATA",
  COLUMNS_DATA_LOADED: "COLUMNS_DATA_LOADED",
  COLUMNS_DATA_LOAD_ERROR: "COLUMNS_DATA_LOAD_ERROR",
  ALL_ROWS_LOADING_DATA: "ALL_ROWS_LOADING_DATA",
  ALL_ROWS_DATA_LOADED: "ALL_ROWS_DATA_LOADED",
  ALL_ROWS_DATA_LOAD_ERROR: "ALL_ROWS_DATA_LOAD_ERROR",
  TOGGLE_COLUMN_VISIBILITY: "TOGGLE_COLUMN_VISIBILITY",
  HIDE_ALL_COLUMNS:"HIDE_ALL_COLUMNS",
  SHOW_ALL_COLUMNS:"SHOW_ALL_COLUMNS"
};

export default actionTypes;
