const actionTypes = {
  TABLE_LOADING_DATA: "TABLE_LOADING_DATA",
  TABLE_DATA_LOADED: "TABLE_DATA_LOADED",
  TABLE_DATA_LOAD_ERROR: "TABLE_DATA_LOAD_ERROR",
  COLUMNS_LOADING_DATA: "COLUMNS_LOADING_DATA",
  COLUMNS_DATA_LOADED: "COLUMNS_DATA_LOADED",
  COLUMNS_DATA_LOAD_ERROR: "COLUMNS_DATA_LOAD_ERROR",
  ALL_ROWS_LOADING_DATA: "ALL_ROWS_LOADING_DATA",
  ALL_ROWS_DATA_LOADED: "ALL_ROWS_DATA_LOADED",
  ALL_ROWS_DATA_LOAD_ERROR: "ALL_ROWS_DATA_LOAD_ERROR",
  TOGGLE_COLUMN_VISIBILITY: "TOGGLE_COLUMN_VISIBILITY",
  HIDE_ALL_COLUMNS:"HIDE_ALL_COLUMNS",
  SET_COLUMNS_VISIBLE:"SET_COLUMNS_VISIBLE",
  SET_FILTERS_AND_SORTING:"SET_FILTERS_AND_SORTING",
  SET_CURRENT_TABLE:"SET_CURRENT_TABLE",
  DELETE_FILTERS:"DELETE_FILTERS",
  GENERATED_DISPLAY_VALUES:"GENERATE_DISPLAY_VALUES",
  START_GENERATING_DISPLAY_VALUES:"START_GENERATING_DISPLAY_VALUES",
  SET_CURRENT_LANGUAGE:"SET_CURRENT_LANGUAGE",
  SET_DISPLAY_VALUE_WORKER:"SET_DISPLAY_VALUE_WORKER"
};

export default actionTypes;
