const actionTypes = {
  TABLE_LOADING_DATA: "TABLE_LOADING_DATA",
  TABLE_DATA_LOADED: "TABLE_DATA_LOADED",
  TABLE_DATA_LOAD_ERROR: "TABLE_DATA_LOAD_ERROR",
  COLUMNS_LOADING_DATA:"COLUMNS_LOADING_DATA",
  COLUMNS_DATA_LOADED:"COLUMNS_DATA_LOADED",
  COLUMNS_DATA_LOAD_ERROR:"COLUMNS_DATA_LOAD_ERROR",
  ALL_ROWS_LOADING_DATA:"ALL_ROWS_LOADING_DATA",
  ALL_ROWS_DATA_LOADED:"ALL_ROWS_DATA_LOADED",
  ALL_ROWS_DATA_LOAD_ERROR:"ALL_ROWS_DATA_LOAD_ERROR"
};

export default actionTypes;
